// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD33ZzZvhT2LoHIzYGmTbnh-j_O7maFGjA',
    appId: '1:761218317880:web:a835fcd7211d21d8d4f0cd',
    messagingSenderId: '761218317880',
    projectId: 'pinfo-3ef73',
    authDomain: 'pinfo-3ef73.firebaseapp.com',
    storageBucket: 'pinfo-3ef73.firebasestorage.app',
    measurementId: 'G-QGB5GZCV38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR2MFo20F1iRB9XVt2BVy0x39EjxMFxcs',
    appId: '1:761218317880:android:4d5e4715a09c651fd4f0cd',
    messagingSenderId: '761218317880',
    projectId: 'pinfo-3ef73',
    storageBucket: 'pinfo-3ef73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlipGFemEuc3Xntx5jmQo8a6Z69RO-WEA',
    appId: '1:761218317880:ios:7c0fb517836b0c64d4f0cd',
    messagingSenderId: '761218317880',
    projectId: 'pinfo-3ef73',
    storageBucket: 'pinfo-3ef73.firebasestorage.app',
    iosClientId: '761218317880-b8o96ulnmr0bsu3515eb33og3gkt2nu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gocare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlipGFemEuc3Xntx5jmQo8a6Z69RO-WEA',
    appId: '1:761218317880:ios:7c0fb517836b0c64d4f0cd',
    messagingSenderId: '761218317880',
    projectId: 'pinfo-3ef73',
    storageBucket: 'pinfo-3ef73.firebasestorage.app',
    iosClientId: '761218317880-b8o96ulnmr0bsu3515eb33og3gkt2nu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gocare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD33ZzZvhT2LoHIzYGmTbnh-j_O7maFGjA',
    appId: '1:761218317880:web:e798255adb992644d4f0cd',
    messagingSenderId: '761218317880',
    projectId: 'pinfo-3ef73',
    authDomain: 'pinfo-3ef73.firebaseapp.com',
    storageBucket: 'pinfo-3ef73.firebasestorage.app',
    measurementId: 'G-E55GWSBY94',
  );
}
